travis:
  secure:
    BINSTAR_TOKEN: bdscRa8p5psbwElsOU2PjzkqKQngYiikWLCP96FBVPKJTfaM0H6/AyUuH7D8wOznoX4yrpm+J481pNXVPb9uBFBODGU47QKhImI68qnMlqo3yyZt+3c4rNDcBjtvTjSbPOqiLyMh7x8UZBXMI70CV5Rcgb3/QWbdmU6GhIt4J+2rE6KjuNFRSWh+hGx+6JxMYEf2ueghtmM1citDlOJf8mk96y+3RBzyU0DsPylXQ4TTmLZ0idBBAHYwxNtepq0TNMYC9vP8HXvyj6qYKtTb42fhSiR6AM5iBxOI2S2W18HnwKL5sJwiRT/+IFusKqeRln+nNgxGRmITJqk1AW3LOSP/2ju/30P+pc+An9S/gsf8ii3tlSPAEOLPx6WGw7Oqy5vuoK8Ir3ULm/u6zgAln24wdoKcrc362CkQz5PNqifv9BSYTM2774GGoVW6dkE/wXy3pfdVhVt0bxc/juKfBnrbW/4VJcijGsPq+qkc92hqBDAumWaOOOKPoBkK8dKHjfC3Qh6OMm/Ew8oMpYGFzJFg4Kiqh5wfRhLafJdpOMKwln80wA/z1rp0Vjjo79Kq6X9CbBeYFAEIXg29ADfhvqK7Iwm+DGh3s9QEo88vWs6K+vcGbX90n3lW5lOphitlCSi4e+cPhrVjmmrjjKVJXMW7i36R5RrplUOw/hjTIl0=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
